In [5]:
from pathlib import Path
import random

import numpy as np
import pandas as pd


# -----------------------------
# 1. Make random results repeatable
# -----------------------------
SEED = 42

random.seed(SEED)
np.random.seed(SEED)


# -----------------------------
# 2. Find the main project folder
# -----------------------------
# Notebook location:
# controlsight/src/data_generation/generate_raw_data.ipynb

ROOT = Path.cwd().parents[1]


# -----------------------------
# 3. Point to the raw data folder
# -----------------------------
RAW = ROOT / "data" / "raw"

RAW.mkdir(parents=True, exist_ok=True)


# -----------------------------
# 4. Set the reporting cut-off date
# -----------------------------
REPORTING_END = pd.Timestamp("2026-09-30")


# -----------------------------
# 5. Check that paths are correct
# -----------------------------
print("Project root:")
print(ROOT)

print("\nRaw data folder:")
print(RAW)

print("\nReporting end date:")
print(REPORTING_END)

Project root:
/Users/ansh/Desktop/ControlSight

Raw data folder:
/Users/ansh/Desktop/ControlSight/data/raw

Reporting end date:
2026-09-30 00:00:00

In [7]:
projects = pd.DataFrame([
    [
        "PRJ-001",
        "Orion Commercial Tower",
        "Commercial Tower",
        "London",
        "2025-01-01",
        "2026-12-31",
        28_000_000,
        "A. Khan",
        "Active",
        "GBP",
        0.98,
        0.98,
    ],
    [
        "PRJ-002",
        "Atlas Data Centre",
        "Data Centre",
        "Manchester",
        "2025-03-01",
        "2027-02-28",
        42_000_000,
        "M. Patel",
        "Active",
        "GBP",
        0.94,
        0.91,
    ],
    [
        "PRJ-003",
        "Riverside Residential",
        "Residential Development",
        "Birmingham",
        "2025-01-15",
        "2026-10-31",
        19_000_000,
        "S. Morgan",
        "Active",
        "GBP",
        0.83,
        0.84,
    ],
    [
        "PRJ-004",
        "NorthLink Infrastructure",
        "Infrastructure",
        "Leeds",
        "2024-11-01",
        "2027-06-30",
        55_000_000,
        "L. Evans",
        "Active",
        "GBP",
        1.01,
        0.99,
    ],
    [
        "PRJ-005",
        "Phoenix Industrial Facility",
        "Industrial Facility",
        "Sheffield",
        "2025-06-01",
        "2027-03-31",
        36_000_000,
        "R. Jones",
        "Active",
        "GBP",
        0.96,
        0.95,
    ],
    [
        "PRJ-006",
        "St Anne Hospital Expansion",
        "Hospital Expansion",
        "Liverpool",
        "2025-02-01",
        "2026-11-30",
        31_000_000,
        "D. Clarke",
        "Active",
        "GBP",
        0.88,
        0.86,
    ],
    [
        "PRJ-007",
        "WestGate Logistics Hub",
        "Logistics Hub",
        "Bristol",
        "2025-08-01",
        "2027-01-31",
        24_000_000,
        "N. Taylor",
        "Active",
        "GBP",
        1.02,
        1.01,
    ],
    [
        "PRJ-008",
        "Helios Energy Facility",
        "Energy Facility",
        "Newcastle",
        "2025-04-01",
        "2027-05-31",
        48_000_000,
        "P. Singh",
        "Active",
        "GBP",
        0.93,
        0.90,
    ],
], columns=[
    "project_code",
    "project_name",
    "project_type",
    "region",
    "start_date",
    "planned_end_date",
    "approved_budget",
    "project_manager",
    "status",
    "currency",
    "cost_health",
    "schedule_health",
])

projects

,project_code,project_name,project_type,region,start_date,planned_end_date,approved_budget,project_manager,status,currency,cost_health,schedule_health
0,PRJ-001,Orion Commercial Tower,Commercial Tower,London,2025-01-01,2026-12-31,28000000,A. Khan,Active,GBP,0.98,0.98
1,PRJ-002,Atlas Data Centre,Data Centre,Manchester,2025-03-01,2027-02-28,42000000,M. Patel,Active,GBP,0.94,0.91
2,PRJ-003,Riverside Residential,Residential Development,Birmingham,2025-01-15,2026-10-31,19000000,S. Morgan,Active,GBP,0.83,0.84
3,PRJ-004,NorthLink Infrastructure,Infrastructure,Leeds,2024-11-01,2027-06-30,55000000,L. Evans,Active,GBP,1.01,0.99
4,PRJ-005,Phoenix Industrial Facility,Industrial Facility,Sheffield,2025-06-01,2027-03-31,36000000,R. Jones,Active,GBP,0.96,0.95
5,PRJ-006,St Anne Hospital Expansion,Hospital Expansion,Liverpool,2025-02-01,2026-11-30,31000000,D. Clarke,Active,GBP,0.88,0.86
6,PRJ-007,WestGate Logistics Hub,Logistics Hub,Bristol,2025-08-01,2027-01-31,24000000,N. Taylor,Active,GBP,1.02,1.01
7,PRJ-008,Helios Energy Facility,Energy Facility,Newcastle,2025-04-01,2027-05-31,48000000,P. Singh,Active,GBP,0.93,0.90

In [8]:
vendors = pd.DataFrame({
    "vendor_id": [
        f"V-{i:03d}"
        for i in range(1, 31)
    ],

    "vendor_name": [
        f"Vendor {i:02d} Ltd"
        for i in range(1, 31)
    ],

    "vendor_category": np.random.choice(
        [
            "Civil",
            "Electrical",
            "Mechanical",
            "HVAC",
            "Steel",
            "IT/Controls",
        ],
        30,
    ),

    "country": np.random.choice(
        [
            "UK",
            "Germany",
            "France",
            "Netherlands",
            "Spain",
        ],
        30,
        p=[0.60, 0.10, 0.10, 0.10, 0.10],
    ),
})

vendors

   vendor_id    vendor_name vendor_category      country
0      V-001  Vendor 01 Ltd            HVAC      Germany
1      V-002  Vendor 02 Ltd           Steel           UK
2      V-003  Vendor 03 Ltd      Mechanical           UK
3      V-004  Vendor 04 Ltd           Steel           UK
4      V-005  Vendor 05 Ltd           Steel           UK
5      V-006  Vendor 06 Ltd      Electrical       France
6      V-007  Vendor 07 Ltd      Mechanical           UK
7      V-008  Vendor 08 Ltd      Mechanical           UK
8      V-009  Vendor 09 Ltd      Mechanical           UK
9      V-010  Vendor 10 Ltd           Steel           UK
10     V-011  Vendor 11 Ltd            HVAC      Germany
11     V-012  Vendor 12 Ltd      Mechanical           UK
12     V-013  Vendor 13 Ltd     IT/Controls           UK
13     V-014  Vendor 14 Ltd           Steel        Spain
14     V-015  Vendor 15 Ltd      Electrical        Spain
15     V-016  Vendor 16 Ltd            HVAC  Netherlands
16     V-017  Vendor 17 Ltd     IT/Controls           UK
17     V-018  Vendor 18 Ltd     IT/Controls           UK
18     V-019  Vendor 19 Ltd      Electrical      Germany
19     V-020  Vendor 20 Ltd            HVAC           UK
20     V-021  Vendor 21 Ltd           Steel           UK
21     V-022  Vendor 22 Ltd           Civil           UK
22     V-023  Vendor 23 Ltd            HVAC           UK
23     V-024  Vendor 24 Ltd      Electrical        Spain
24     V-025  Vendor 25 Ltd     IT/Controls           UK
25     V-026  Vendor 26 Ltd           Steel      Germany
26     V-027  Vendor 27 Ltd            HVAC           UK
27     V-028  Vendor 28 Ltd           Civil           UK
28     V-029  Vendor 29 Ltd           Civil           UK
29     V-030  Vendor 30 Ltd      Mechanical           UK

In [9]:
categories = [
    "Civil",
    "Structural",
    "Mechanical",
    "Electrical",
    "HVAC",
    "IT/Controls",
]


package_rows = []

for _, project in projects.iterrows():

    # Create 12 budget shares that together add up to 100%
    weights = np.random.dirichlet(
        np.ones(12)
    )

    for i in range(1, 13):

        category = categories[
            (i - 1) % len(categories)
        ]

        package_rows.append({
            "package_code":
                f"{project.project_code}-PKG-{i:02d}",

            "project_code":
                project.project_code,

            "package_name":
                f"{category} Package {i:02d}",

            "cost_category":
                category,

            "package_budget":
                round(
                    project.approved_budget
                    * weights[i - 1],
                    2,
                ),
        })


packages = pd.DataFrame(package_rows)

packages

,package_code,project_code,package_name,cost_category,package_budget
0,PRJ-001-PKG-01,PRJ-001,Civil Package 01,Civil,6493032.57
1,PRJ-001-PKG-02,PRJ-001,Structural Package 02,Structural,2774043.19
2,PRJ-001-PKG-03,PRJ-001,Mechanical Package 03,Mechanical,5214593.51
3,PRJ-001-PKG-04,PRJ-001,Electrical Package 04,Electrical,4186688.73
4,PRJ-001-PKG-05,PRJ-001,HVAC Package 05,HVAC,1693625.14
...,...,...,...,...,...
91,PRJ-008-PKG-08,PRJ-008,Structural Package 08,Structural,979846.30
92,PRJ-008-PKG-09,PRJ-008,Mechanical Package 09,Mechanical,2322958.67
93,PRJ-008-PKG-10,PRJ-008,Electrical Package 10,Electrical,1209112.84
94,PRJ-008-PKG-11,PRJ-008,HVAC Package 11,HVAC,1132495.65
95,PRJ-008-PKG-12,PRJ-008,IT/Controls Package 12,IT/Controls,126962.86

In [10]:
budget_check = (
    packages
    .groupby("project_code", as_index=False)["package_budget"]
    .sum()
    .rename(columns={"package_budget": "sum_of_package_budgets"})
)

budget_check = budget_check.merge(
    projects[
        ["project_code", "approved_budget"]
    ],
    on="project_code",
    how="left",
)

budget_check["difference"] = (
    budget_check["sum_of_package_budgets"]
    - budget_check["approved_budget"]
)

budget_check

  project_code  sum_of_package_budgets  approved_budget  difference
0      PRJ-001             28000000.00         28000000        0.00
1      PRJ-002             42000000.00         42000000        0.00
2      PRJ-003             19000000.01         19000000        0.01
3      PRJ-004             54999999.99         55000000       -0.01
4      PRJ-005             36000000.02         36000000        0.02
5      PRJ-006             31000000.00         31000000        0.00
6      PRJ-007             23999999.98         24000000       -0.02
7      PRJ-008             48000000.02         48000000        0.02

In [11]:
# Empty lists where we will collect our generated records
progress_rows = []
cost_rows = []


for _, project in projects.iterrows():

    # Convert the project's start date to the end of that month
    start = (
        pd.Timestamp(project.start_date)
        .to_period("M")
        .to_timestamp("M")
    )

    # We only generate data up to our reporting cut-off date
    end = min(
        REPORTING_END,
        pd.Timestamp(project.planned_end_date)
        .to_period("M")
        .to_timestamp("M"),
    )

    # All reporting months between project start and reporting cut-off
    months = pd.date_range(
        start,
        end,
        freq="ME",
    )

    # All months across the project's complete planned lifetime
    full_project_months = pd.date_range(
        start,
        pd.Timestamp(project.planned_end_date)
        .to_period("M")
        .to_timestamp("M"),
        freq="ME",
    )

    total_months = max(
        len(full_project_months),
        1,
    )

    # Find only the cost packages belonging to this project
    project_packages = packages[
        packages["project_code"] == project.project_code
    ].copy()

    print(
        project.project_code,
        "| reporting months:",
        len(months),
        "| total planned months:",
        total_months,
        "| packages:",
        len(project_packages),
    )

PRJ-001 | reporting months: 21 | total planned months: 24 | packages: 12
PRJ-002 | reporting months: 19 | total planned months: 24 | packages: 12
PRJ-003 | reporting months: 21 | total planned months: 22 | packages: 12
PRJ-004 | reporting months: 23 | total planned months: 32 | packages: 12
PRJ-005 | reporting months: 16 | total planned months: 22 | packages: 12
PRJ-006 | reporting months: 20 | total planned months: 22 | packages: 12
PRJ-007 | reporting months: 14 | total planned months: 18 | packages: 12
PRJ-008 | reporting months: 18 | total planned months: 26 | packages: 12

In [12]:
progress_rows = []

for _, project in projects.iterrows():

    start = (
        pd.Timestamp(project.start_date)
        .to_period("M")
        .to_timestamp("M")
    )

    end = min(
        REPORTING_END,
        pd.Timestamp(project.planned_end_date)
        .to_period("M")
        .to_timestamp("M"),
    )

    months = pd.date_range(
        start,
        end,
        freq="ME",
    )

    full_project_months = pd.date_range(
        start,
        pd.Timestamp(project.planned_end_date)
        .to_period("M")
        .to_timestamp("M"),
        freq="ME",
    )

    total_months = max(
        len(full_project_months),
        1,
    )

    for month_number, month in enumerate(
        months,
        start=1,
    ):

        planned_progress = min(
            100,
            (
                month_number
                / total_months
            ) * 100,
        )

        actual_progress = min(
            100,
            max(
                0,
                planned_progress
                * project.schedule_health
                + np.random.normal(
                    0,
                    1.5,
                ),
            ),
        )

        progress_rows.append({
            "project_code":
                project.project_code,

            "report_month":
                month.strftime("%Y-%m-%d"),

            "planned_progress_pct":
                round(
                    planned_progress,
                    2,
                ),

            "actual_progress_pct":
                round(
                    actual_progress,
                    2,
                ),

            "reported_by":
                np.random.choice([
                    "PMO",
                    "Site Team",
                    "Project Controls",
                ]),

            "source_system":
                "P6_EXPORT",
        })


progress = pd.DataFrame(progress_rows)

progress

,project_code,report_month,planned_progress_pct,actual_progress_pct,reported_by,source_system
0,PRJ-001,2025-01-31,4.17,4.17,Site Team,P6_EXPORT
1,PRJ-001,2025-02-28,8.33,11.86,Project Controls,P6_EXPORT
2,PRJ-001,2025-03-31,12.50,12.97,Project Controls,P6_EXPORT
3,PRJ-001,2025-04-30,16.67,15.94,Site Team,P6_EXPORT
4,PRJ-001,2025-05-31,20.83,20.36,Site Team,P6_EXPORT
...,...,...,...,...,...,...
147,PRJ-008,2026-05-31,53.85,49.46,Project Controls,P6_EXPORT
148,PRJ-008,2026-06-30,57.69,51.90,Project Controls,P6_EXPORT
149,PRJ-008,2026-07-31,61.54,54.04,Site Team,P6_EXPORT
150,PRJ-008,2026-08-31,65.38,55.71,Project Controls,P6_EXPORT
151,PRJ-008,2026-09-30,69.23,64.96,PMO,P6_EXPORT

In [13]:
latest_progress = (
    progress
    .sort_values(["project_code", "report_month"])
    .groupby("project_code")
    .tail(1)
    .copy()
)

latest_progress["progress_variance"] = (
    latest_progress["actual_progress_pct"]
    - latest_progress["planned_progress_pct"]
)

latest_progress[
    [
        "project_code",
        "report_month",
        "planned_progress_pct",
        "actual_progress_pct",
        "progress_variance",
    ]
]

,project_code,report_month,planned_progress_pct,actual_progress_pct,progress_variance
20,PRJ-001,2026-09-30,87.50,87.50,0.00
39,PRJ-002,2026-09-30,79.17,72.00,-7.17
60,PRJ-003,2026-09-30,95.45,80.44,-15.01
83,PRJ-004,2026-09-30,71.88,71.79,-0.09
99,PRJ-005,2026-09-30,72.73,70.25,-2.48
119,PRJ-006,2026-09-30,90.91,76.28,-14.63
133,PRJ-007,2026-09-30,77.78,79.10,1.32
151,PRJ-008,2026-09-30,69.23,64.96,-4.27

In [14]:
cost_rows = []

for _, project in projects.iterrows():

    start = (
        pd.Timestamp(project.start_date)
        .to_period("M")
        .to_timestamp("M")
    )

    end = min(
        REPORTING_END,
        pd.Timestamp(project.planned_end_date)
        .to_period("M")
        .to_timestamp("M"),
    )

    months = pd.date_range(
        start,
        end,
        freq="ME",
    )

    full_project_months = pd.date_range(
        start,
        pd.Timestamp(project.planned_end_date)
        .to_period("M")
        .to_timestamp("M"),
        freq="ME",
    )

    total_months = max(
        len(full_project_months),
        1,
    )

    project_packages = packages[
        packages["project_code"] == project.project_code
    ].copy()

    for month_number, month in enumerate(
        months,
        start=1,
    ):

        monthly_weight = (
            (1 / total_months)
            * (
                0.65
                + 0.7
                * np.sin(
                    np.pi
                    * min(
                        month_number / total_months,
                        1,
                    )
                )
            )
        )

        for _, package in project_packages.iterrows():

            planned = (
                package.package_budget
                * monthly_weight
            )

            cost_noise = np.random.normal(
                1.0 / project.cost_health,
                0.08,
            )

            actual = max(
                0,
                planned * cost_noise,
            )

            committed = max(
                actual,
                planned
                * np.random.uniform(
                    1.00,
                    1.20,
                ),
            )

            forecast = (
                package.package_budget
                / project.cost_health
                * np.random.uniform(
                    0.98,
                    1.03,
                )
            )

            cost_rows.append({
                "cost_record_id":
                    f"C-{len(cost_rows)+1:06d}",

                "project_code":
                    project.project_code,

                "package_code":
                    package.package_code,

                "cost_category":
                    package.cost_category,

                "report_month":
                    month.strftime("%Y-%m-%d"),

                "planned_cost":
                    round(planned, 2),

                "actual_cost":
                    round(actual, 2),

                "committed_cost":
                    round(committed, 2),

                "forecast_at_completion":
                    round(forecast, 2),

                "currency":
                    "GBP",

                "source_system":
                    "ERP_COST",
            })


costs = pd.DataFrame(cost_rows)

costs

,cost_record_id,project_code,package_code,cost_category,report_month,planned_cost,actual_cost,committed_cost,forecast_at_completion,currency,source_system
0,C-000001,PRJ-001,PRJ-001-PKG-01,Civil,2025-01-31,200572.03,191419.61,206308.06,6745303.66,GBP,ERP_COST
1,C-000002,PRJ-001,PRJ-001-PKG-02,Structural,2025-01-31,85691.16,85236.76,96286.32,2788355.37,GBP,ERP_COST
2,C-000003,PRJ-001,PRJ-001-PKG-03,Mechanical,2025-01-31,161080.60,167524.71,167524.71,5433249.95,GBP,ERP_COST
3,C-000004,PRJ-001,PRJ-001-PKG-04,Electrical,2025-01-31,129328.27,126722.65,147595.69,4204065.36,GBP,ERP_COST
4,C-000005,PRJ-001,PRJ-001-PKG-05,HVAC,2025-01-31,52316.67,47323.64,60821.26,1775476.36,GBP,ERP_COST
...,...,...,...,...,...,...,...,...,...,...,...
1819,C-001820,PRJ-008,PRJ-008-PKG-08,Structural,2026-09-30,46206.86,57233.81,57233.81,1057060.59,GBP,ERP_COST
1820,C-001821,PRJ-008,PRJ-008-PKG-09,Mechanical,2026-09-30,109544.36,116160.28,119523.10,2520553.13,GBP,ERP_COST
1821,C-001822,PRJ-008,PRJ-008-PKG-10,Electrical,2026-09-30,57018.45,54014.56,61086.95,1284797.48,GBP,ERP_COST
1822,C-001823,PRJ-008,PRJ-008-PKG-11,HVAC,2026-09-30,53405.39,62928.36,62928.36,1213984.67,GBP,ERP_COST
1823,C-001824,PRJ-008,PRJ-008-PKG-12,IT/Controls,2026-09-30,5987.22,6444.82,7107.46,140015.51,GBP,ERP_COST

In [15]:
activity_rows = []

activity_names = [
    "Design approval",
    "Site mobilisation",
    "Groundworks",
    "Structural frame",
    "MEP installation",
    "Electrical installation",
    "HVAC installation",
    "Testing & commissioning",
    "Quality inspection",
    "Client handover",
]

for _, project in projects.iterrows():

    project_start = pd.Timestamp(
        project.start_date
    )

    for i in range(1, 41):

        planned_start = (
            project_start
            + pd.Timedelta(
                days=(i - 1) * 12
                + np.random.randint(0, 8)
            )
        )

        duration = np.random.randint(
            10,
            46,
        )

        planned_finish = (
            planned_start
            + pd.Timedelta(
                days=duration
            )
        )

        delay_bias = max(
            0,
            (1 - project.schedule_health) * 90,
        )

        start_delay = max(
            0,
            int(
                np.random.normal(
                    delay_bias * 0.35,
                    4,
                )
            ),
        )

        finish_delay = max(
            0,
            int(
                np.random.normal(
                    delay_bias,
                    7,
                )
            ),
        )

        actual_start = (
            planned_start
            + pd.Timedelta(
                days=start_delay
            )
        )

        actual_finish = (
            planned_finish
            + pd.Timedelta(
                days=finish_delay
            )
        )

        if planned_start > REPORTING_END:

            status = "Not Started"
            percent_complete = 0
            actual_start_output = ""
            actual_finish_output = ""

        elif actual_finish <= REPORTING_END:

            status = "Complete"
            percent_complete = 100

            actual_start_output = (
                actual_start.strftime("%Y-%m-%d")
            )

            actual_finish_output = (
                actual_finish.strftime("%Y-%m-%d")
            )

        else:

            status = "In Progress"

            elapsed = (
                REPORTING_END
                - actual_start
            ).days

            percent_complete = round(
                max(
                    5,
                    min(
                        95,
                        elapsed
                        / max(
                            duration + finish_delay,
                            1,
                        )
                        * 100,
                    ),
                ),
                1,
            )

            actual_start_output = (
                actual_start.strftime("%Y-%m-%d")
            )

            actual_finish_output = ""

        activity_rows.append({
            "activity_id":
                f"{project.project_code}-ACT-{i:03d}",

            "project_code":
                project.project_code,

            "wbs_code":
                f"WBS-{((i - 1) // 5) + 1:02d}",

            "activity_name":
                activity_names[
                    (i - 1) % len(activity_names)
                ],

            "discipline":
                categories[
                    (i - 1) % len(categories)
                ],

            "planned_start":
                planned_start.strftime("%Y-%m-%d"),

            "planned_finish":
                planned_finish.strftime("%Y-%m-%d"),

            "actual_start":
                actual_start_output,

            "actual_finish":
                actual_finish_output,

            "percent_complete":
                percent_complete,

            "status":
                status,

            "is_critical":
                bool(
                    i % 7 == 0
                    or i % 11 == 0
                ),

            "source_system":
                "P6_EXPORT",
        })


schedule = pd.DataFrame(activity_rows)

schedule

,activity_id,project_code,wbs_code,activity_name,discipline,planned_start,planned_finish,actual_start,actual_finish,percent_complete,status,is_critical,source_system
0,PRJ-001-ACT-001,PRJ-001,WBS-01,Design approval,Civil,2025-01-03,2025-02-06,2025-01-04,2025-02-14,100.0,Complete,False,P6_EXPORT
1,PRJ-001-ACT-002,PRJ-001,WBS-01,Site mobilisation,Structural,2025-01-16,2025-02-19,2025-01-19,2025-02-22,100.0,Complete,False,P6_EXPORT
2,PRJ-001-ACT-003,PRJ-001,WBS-01,Groundworks,Mechanical,2025-01-31,2025-03-13,2025-02-07,2025-03-17,100.0,Complete,False,P6_EXPORT
3,PRJ-001-ACT-004,PRJ-001,WBS-01,Structural frame,Electrical,2025-02-10,2025-03-13,2025-02-10,2025-03-13,100.0,Complete,False,P6_EXPORT
4,PRJ-001-ACT-005,PRJ-001,WBS-01,MEP installation,HVAC,2025-02-20,2025-04-03,2025-02-20,2025-04-03,100.0,Complete,False,P6_EXPORT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,PRJ-008-ACT-036,PRJ-008,WBS-08,Electrical installation,IT/Controls,2026-05-26,2026-06-11,2026-05-26,2026-06-25,100.0,Complete,False,P6_EXPORT
316,PRJ-008-ACT-037,PRJ-008,WBS-08,HVAC installation,Civil,2026-06-14,2026-07-18,2026-06-16,2026-08-04,100.0,Complete,False,P6_EXPORT
317,PRJ-008-ACT-038,PRJ-008,WBS-08,Testing & commissioning,Structural,2026-06-26,2026-08-03,2026-07-03,2026-08-06,100.0,Complete,False,P6_EXPORT
318,PRJ-008-ACT-039,PRJ-008,WBS-08,Quality inspection,Mechanical,2026-07-08,2026-08-13,2026-07-15,2026-08-20,100.0,Complete,False,P6_EXPORT
319,PRJ-008-ACT-040,PRJ-008,WBS-08,Client handover,Electrical,2026-07-17,2026-08-07,2026-07-22,2026-08-09,100.0,Complete,False,P6_EXPORT

In [16]:
procurement_rows = []


for _, package in packages.iterrows():

    project = projects[
        projects["project_code"]
        == package.project_code
    ].iloc[0]

    # Most cost packages will have 1 procurement order.
    # Some will have 2.
    number_of_orders = np.random.choice([
        1,
        1,
        1,
        2,
    ])


    for _ in range(number_of_orders):

        # Request for quotation date
        rfq_date = (
            pd.Timestamp(
                project.start_date
            )
            + pd.Timedelta(
                days=np.random.randint(
                    20,
                    240,
                )
            )
        )

        # Purchase order date
        po_date = (
            rfq_date
            + pd.Timedelta(
                days=np.random.randint(
                    10,
                    50,
                )
            )
        )

        # Planned delivery date
        planned_delivery = (
            po_date
            + pd.Timedelta(
                days=np.random.randint(
                    30,
                    120,
                )
            )
        )

        # Projects with worse schedule health
        # are more likely to experience procurement delays
        delay = max(
            0,
            int(
                np.random.normal(
                    max(
                        0,
                        (
                            1
                            - project.schedule_health
                        ) * 80,
                    ),
                    9,
                )
            ),
        )

        actual_delivery = (
            planned_delivery
            + pd.Timedelta(
                days=delay
            )
        )


        # Decide current procurement status
        if planned_delivery > REPORTING_END:

            status = "Ordered"
            actual_delivery_output = ""

        elif actual_delivery <= REPORTING_END:

            status = "Delivered"

            actual_delivery_output = (
                actual_delivery.strftime(
                    "%Y-%m-%d"
                )
            )

        else:

            status = "Delayed"
            actual_delivery_output = ""


        procurement_rows.append({

            "procurement_id":
                f"PO-{len(procurement_rows)+1:05d}",

            "project_code":
                package.project_code,

            "package_code":
                package.package_code,

            "vendor_id":
                np.random.choice(
                    vendors.vendor_id
                ),

            "category":
                package.cost_category,

            "rfq_date":
                rfq_date.strftime(
                    "%Y-%m-%d"
                ),

            "po_date":
                po_date.strftime(
                    "%Y-%m-%d"
                ),

            "planned_delivery_date":
                planned_delivery.strftime(
                    "%Y-%m-%d"
                ),

            "actual_delivery_date":
                actual_delivery_output,

            "package_value":
                round(
                    package.package_budget
                    * np.random.uniform(
                        0.35,
                        0.85,
                    ),
                    2,
                ),

            "status":
                status,

            "criticality":
                np.random.choice(
                    [
                        "Low",
                        "Medium",
                        "High",
                    ],
                    p=[
                        0.25,
                        0.50,
                        0.25,
                    ],
                ),

            "source_system":
                "PROCURE_TRACKER",
        })


procurement = pd.DataFrame(
    procurement_rows
)

procurement

,procurement_id,project_code,package_code,vendor_id,category,rfq_date,po_date,planned_delivery_date,actual_delivery_date,package_value,status,criticality,source_system
0,PO-00001,PRJ-001,PRJ-001-PKG-01,V-004,Civil,2025-08-22,2025-09-09,2025-12-29,2026-01-01,2405511.22,Delivered,Medium,PROCURE_TRACKER
1,PO-00002,PRJ-001,PRJ-001-PKG-02,V-003,Structural,2025-03-28,2025-04-11,2025-05-24,2025-05-29,1031731.65,Delivered,Medium,PROCURE_TRACKER
2,PO-00003,PRJ-001,PRJ-001-PKG-03,V-016,Mechanical,2025-07-28,2025-08-29,2025-10-24,2025-10-25,1945726.28,Delivered,Medium,PROCURE_TRACKER
3,PO-00004,PRJ-001,PRJ-001-PKG-04,V-023,Electrical,2025-03-22,2025-04-22,2025-08-10,2025-08-10,1716307.99,Delivered,Medium,PROCURE_TRACKER
4,PO-00005,PRJ-001,PRJ-001-PKG-05,V-017,HVAC,2025-01-22,2025-03-04,2025-05-22,2025-05-28,753538.42,Delivered,Low,PROCURE_TRACKER
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,PO-00114,PRJ-008,PRJ-008-PKG-09,V-011,Mechanical,2025-09-29,2025-10-22,2025-12-06,2025-12-13,1781870.35,Delivered,Medium,PROCURE_TRACKER
114,PO-00115,PRJ-008,PRJ-008-PKG-10,V-006,Electrical,2025-05-02,2025-05-17,2025-07-04,2025-07-14,742278.82,Delivered,High,PROCURE_TRACKER
115,PO-00116,PRJ-008,PRJ-008-PKG-11,V-016,HVAC,2025-11-23,2025-12-18,2026-03-09,2026-03-09,653093.60,Delivered,Medium,PROCURE_TRACKER
116,PO-00117,PRJ-008,PRJ-008-PKG-11,V-022,HVAC,2025-07-21,2025-09-06,2025-11-15,2025-11-27,431966.39,Delivered,Medium,PROCURE_TRACKER
117,PO-00118,PRJ-008,PRJ-008-PKG-12,V-003,IT/Controls,2025-05-20,2025-06-13,2025-10-02,2025-10-21,74198.30,Delivered,Medium,PROCURE_TRACKER

In [17]:
# ============================================================
# INTENTIONAL RAW DATA QUALITY PROBLEMS
# ============================================================

# 1. Missing vendor IDs
bad_vendor_rows = procurement.sample(
    frac=0.025,
    random_state=SEED,
).index

procurement.loc[
    bad_vendor_rows,
    "vendor_id",
] = np.nan


# 2. Duplicate procurement record
procurement = pd.concat(
    [
        procurement,
        procurement.iloc[[5]],
    ],
    ignore_index=True,
)


# 3. Invalid / non-existent project reference
costs.loc[
    costs.index[17],
    "project_code",
] = "PRJ-999"


# 4. Negative actual cost
costs.loc[
    costs.index[80],
    "actual_cost",
] = -25_000


# 5. Extreme cost anomaly
costs.loc[
    costs.index[120],
    "actual_cost",
] *= 8


# 6. Missing package code
costs.loc[
    costs.index[180],
    "package_code",
] = np.nan


# 7. Inconsistent date format
progress.loc[
    progress.index[9],
    "report_month",
] = "31/12/2025"


# 8. Impossible progress percentage
progress.loc[
    progress.index[25],
    "actual_progress_pct",
] = 126.0


# 9. Actual finish before actual start
schedule_row = schedule.index[30]

schedule.loc[
    schedule_row,
    "actual_start",
] = "2026-06-20"

schedule.loc[
    schedule_row,
    "actual_finish",
] = "2026-06-10"


# 10. Missing completion percentage
schedule.loc[
    schedule.index[65],
    "percent_complete",
] = np.nan


print("Intentional data-quality problems added successfully.")

Intentional data-quality problems added successfully.

In [18]:
# ============================================================
# EXPORT RAW DATASETS
# ============================================================

# Save projects WITHOUT the simulation helper columns
projects.drop(
    columns=[
        "cost_health",
        "schedule_health",
    ]
).to_csv(
    RAW / "projects.csv",
    index=False,
)

# Save vendors
vendors.to_csv(
    RAW / "vendors.csv",
    index=False,
)

# Save cost packages
packages.to_csv(
    RAW / "cost_packages.csv",
    index=False,
)

# Save monthly costs
costs.to_csv(
    RAW / "cost_monthly.csv",
    index=False,
)

# Save schedule activities
schedule.to_csv(
    RAW / "schedule_activities.csv",
    index=False,
)

# Save procurement data
procurement.to_csv(
    RAW / "procurement_packages.csv",
    index=False,
)

# Save progress data
progress.to_csv(
    RAW / "progress_updates.csv",
    index=False,
)

print("All raw datasets exported successfully.")

All raw datasets exported successfully.

In [19]:
for file in sorted(RAW.glob("*.csv")):
    df = pd.read_csv(file)

    print(
        f"{file.name:30s}"
        f"{len(df):5d} rows x "
        f"{len(df.columns):2d} columns"
    )

cost_monthly.csv               1824 rows x 11 columns
cost_packages.csv                96 rows x  5 columns
procurement_packages.csv        119 rows x 13 columns
progress_updates.csv            152 rows x  6 columns
projects.csv                      8 rows x 10 columns
schedule_activities.csv         320 rows x 13 columns
vendors.csv                      30 rows x  4 columns